BASIC_WAGE = 4420000

HUMAN_NAMES = [
    'Nguyến Quang Anh',
    'Nguyễn Bảo Thiên',
    'Nguyên Hoàng Châu',
    'Ngô Tấn Phát Đạt',
    'Nguyễn Danh Tiến',
    'Võ Văn Dũng',
    'Nguyễn Thế Duy',
    'Trần Đực',
    'Lê Trung Hiếu',
    'Phạm Minh Hiếu',
    'Lê Viết Hào',
    'Huỳnh Kim Hiền',
    'Đặng Anh Khoa',
    'Nguyễn Ánh Linh',
    'Trần Phương Nam',
    'Nguyễn Hồ Hoàng',
    'Nguyễn Quân Lập',
    'Nguyễn Minh Quân',
    'Nguyễn Thái Sơn',
    'Đào Thị Tuyết',
    'Phạm Thiên Anh',
    'Lê Tiến Viết',
    'Trần Toại',
    'Nguyễn Minh Toản',
    'Nguyễn Văn Tú',
    'Văn Kiến Hà',
]


BOOK_NAMES = [
    "Cây Cam Của Bạn",
    "Lời giải tiếng Anh 12",
    "Tâm lý học cơ bản",
    "Nhà hóa học",
    "Đòi nợ",
    "Tù nhân của triết lý",
    "Những con số thay đổi thế giới",
    "Tâm lý học đặc biệt",
    "Giấc mở của Sasa",
    "Chúa và con người",
    "Kiếp sinh nhân",
    "Giảm 10kg trong 2 tuần",
    "Đọc nhanh cảm xúc và ngôn ngữ cơ thể",
    "Bá tước Ca-lốt",
    "Tô vẽ bình yên",
    "Đam mê để làm gì",
    "Mind Map cho người mới bắt đầu",
    "Chinh phục IELTS",
    "Giao tiếp tiếng Nhật",
    "Ngệ thuật làm tiền",
    "Những người vui sướng",
    "WWW 2021",
    "Những con người vĩ đại",
    "Kế toán quản trị cho các doanh nghiệp",
    "Nghệ thuật đầu tư",
    "Trò chơi con mực",
    "Giết chết con chim sẽ",
    "Trên biển",
    "Vãn tình",
    "Hắc dạ hành",
    "Mẹ giàu mẹ nghèo",
    "Chú bé đội mũ trắng",
]



LAST_NAMES = [
    "Nguyễn", "Trần", "Lê", "Phạm",
    "Hoàng", "Huỳnh", "Phan", "Vũ",
    "Võ", "Đặng", "Bùi", "Đỗ", "Hồ",
    "Ngô", "Dương", "Lý",
]

MIDDLE_NAMES = [
    "", "Thanh", "Gia", "Anh",
]

FIRST_NAMES = [
    "Ái",
    "An",
    "Anh",
    "Ánh",
    "Ân",
    "Ẩn",
    "Âu",
    "Ba",
    "Bá",
    "Bạc",
    "Bách",
    "Bạch",
    "Bài",
    "Ban",
    "Bàng",
    "Bảng",
    "Báo",
    "Bào",
    "Bảo",
    "Bạt",
    "Báu",
    "Bắc",
    "Bằng",
    "Bặt",
    "Bân",
    "Bật",
    "Bến",
    "Bền",
    "Bi",
    "Bích",
    "Biên",
    "Biền",
    "Biện",
    "Biểu",
    "Bính",
    "Bình",
    "Bố",
    "Bổ",
    "Bộ",
    "Bốc",
    "Bộc",
    "Bôi",
    "Bối",
    "Bồi",
    "Bội",
    "Bôn",
    "Bốn",
    "Bổn",
    "Bông",
    "Bồng",
    "Bổng",
    "Bột",
    "Bùi",
    "Buông",
    "Bút",
    "Bưng",
    "Bưu",
    "Ca",
    "Cai",
    "Cam",
    "Can",
    "Canh",
    "Cảnh",
    "Cán",
    "Cao",
    "Cảo",
    "Cát",
    "Căn",
    "Cầm",
    "Cẩm",
    "Cần",
    "Cẩn",
    "Cận",
    "Cật",
    "Câu",
    "Cầu",
    "Chanh",
    "Chánh",
    "Chăm",
    "Châm",
    "Chân",
    "Chấn",
    "Chẩn",
    "Chấp",
    "Chất",
    "Châu",
    "Chế",
    "Chi",
    "Chí",
    "Chỉ",
    "Chiêm",
    "Chiếm",
    "Chiến",
    "Chiêu",
    "Chiếu",
    "Chinh",
    "Chính",
    "Chình",
    "Chỉnh",
    "Chu",
    "Chú",
    "Chủ",
    "Chúa",
    "Chúc",
    "Chung",
    "Chủng",
    "Chuyên",
    "Chuyển",
    "Chư",
    "Chử",
    "Chức",
    "Chước",
    "Chương",
    "Chưởng",
    "Cổ",
    "Côn",
    "Cổn",
    "Công",
    "Cống",
    "Cơ",
    "Cú",
    "Cù",
    "Cúc",
    "Cung",
    "Củng",
    "Cư",
    "Cứ",
    "Cừ",
    "Cử",
    "Cự",
    "Cương",
    "Cường",
    "Cửu",
    "Cữu",
    "Cựu",
    "Danh",
    "Dao",
    "Dân",
    "Dần",
    "Dẫn",
    "Dật",
    "Di",
    "Dị",
    "Dịch",
    "Diêm",
    "Diễm",
    "Diệm",
    "Diếp",
    "Diệp",
    "Diệu",
    "Dinh",
    "Dĩnh",
    "Do",
    "Doãn",
    "Doanh",
    "Du",
    "Dũ",
    "Dụ",
    "Duật",
    "Dục",
    "Duệ",
    "Dung",
    "Dũng",
    "Dụng",
    "Duy",
    "Duyên",
    "Duyệt",
    "Dư",
    "Dự",
    "Dực",
    "Dược",
    "Dương",
    "Dưỡng",
    "Ðạc",
    "Ðãi",
    "Ðại",
    "Ðam",
    "Ðàm",
    "Ðảm",
    "Ðạm",
    "Ðan",
    "Ðán",
    "Ðàn",
    "Ðản",
    "Ðào",
    "Ðang",
    "Ðàng",
    "Ðảng",
    "Ðào",
    "Ðảo",
    "Ðạo",
    "Ðạt",
    "Ðắc",
    "Ðăng",
    "Ðằng",
    "Ðẳng",
    "Ðẩu",
    "Ðậu",
    "Ðể",
    "Ðệ",
    "Ðiềm",
    "Ðiền",
    "Ðiệp",
    "Ðiều",
    "Ðiểu",
    "Ðinh",
    "Ðính",
    "Ðình",
    "Ðỉnh",
    "Ðĩnh",
    "Ðịnh",
    "Ðoá",
    "Ðoài",
    "Ðoái",
    "Ðoan",
    "Ðoàn",
    "Ðô",
    "Ðổ",
    "Ðộ",
    "Ðốc",
    "Ðối",
    "Ðôn",
    "Ðông",
    "Ðồng",
    "Ðổng",
    "Ðới",
    "Ðơn",
    "Ðủ",
    "Ðức",
    "Ðược",
    "Ðương",
    "Ðường",
    "Em",
    "Gia",
    "Giá",
    "Giả",
    "Giác",
    "Giai",
    "Giải",
    "Giám",
    "Gián",
    "Giản",
    "Giang",
    "Giảng",
    "Giao",
    "Giáo",
    "Giáp",
    "Giàu",
    "Giới",
    "Giũ",
    "Hà",
    "Hạ",
    "Hạc",
    "Hách",
    "Hai",
    "Hài",
    "Hải",
    "Hàm",
    "Hán",
    "Hàn",
    "Hãn",
    "Hạn",
    "Hạng",
    "Hanh",
    "Hành",
    "Hạnh",
    "Hào",
    "Hảo",
    "Hạo",
    "Hạp",
    "Hạt",
    "Hằng",
    "Hân",
    "Hậu",
    "Hiến",
    "Hiền",
    "Hiển",
    "Hiệp",
    "Hiệt",
    "Hiếu",
    "Hiểu",
    "Hiệu",
    "Hinh",
    "Hoa",
    "Hoá",
    "Hoà",
    "Hoạch",
    "Hoài",
    "Hoán",
    "Hoàn",
    "Hoàng",
    "Hoành",
    "Hoạnh",
    "Học",
    "Hoạt",
    "Hồ",
    "Hổ",
    "Hộ",
    "Hối",
    "Hồi",
    "Hội",
    "Hồng",
    "Hợp",
    "Huân",
    "Huấn",
    "Huề",
    "Huệ",
    "Hùng",
    "Huy",
    "Huyên",
    "Huyến",
    "Huyền",
    "Huyện",
    "Huynh",
    "Huỳnh",
    "Hứa",
    "Hưng",
    "Hương",
    "Hướng",
    "Hường",
    "Hưởng",
    "Hưu",
    "Hữu",
    "Hựu",
    "Hy",
    "Hỷ",
    "Ích",
    "Keo",
    "Kế",
    "Kết",
    "Kha",
    "Khá",
    "Khả",
    "Khai",
    "Khái",
    "Khải",
    "Kham",
    "Khán",
    "Khang",
    "Kháng",
    "Khảng",
    "Khanh",
    "Khánh",
    "Khảo",
    "Khắc",
    "Khâm",
    "Khẩn",
    "Khấp",
    "Khâu",
    "Khê",
    "Khiêm",
    "Khiết",
    "Khiêu",
    "Khinh",
    "Khoa",
    "Khoá",
    "Khoả",
    "Khoách",
    "Khoái",
    "Khoan",
    "Khoán",
    "Khoát",
    "Khôi",
    "Khôn",
    "Khổng",
    "Khu",
    "Khúc",
    "Khuê",
    "Khuông",
    "Khuyến",
    "Khuyết",
    "Khuynh",
    "Khương",
    "Khưu",
    "Kiêm",
    "Kiểm",
    "Kiệm",
    "Kiên",
    "Kiện",
    "Kiệt",
    "Kiều",
    "Kim",
    "Kinh",
    "Kính",
    "Kỉnh",
    "Kỳ",
    "Kỷ",
    "Kỵ",
    "La",
    "Lạc",
    "Lai",
    "Lài",
    "Lại",
    "Lam",
    "Lãm",
    "Lan",
    "Lang",
    "Lãng",
    "Lanh",
    "Lành",
    "Lãnh",
    "Lạp",
    "Lăng",
    "Lâm",
    "Lân",
    "Lập",
    "Lâu",
    "Lê",
    "Lễ",
    "Lệ",
    "Lịch",
    "Liêm",
    "Liên",
    "Liễn",
    "Liêu",
    "Liễu",
    "Liệu",
    "Linh",
    "Loan",
    "Long",
    "Lô",
    "Lộc",
    "Lôi",
    "Lời",
    "Lợi",
    "Lụa",
    "Luân",
    "Luận",
    "Luật",
    "Lục",
    "Luỹ",
    "Luyến",
    "Luyện",
    "Lư",
    "Lữ",
    "Lực",
    "Lược",
    "Lương",
    "Lượng",
    "Lưu",
    "Lựu",
    "Ly",
    "Lý",
    "Mai",
    "Mại",
    "Mãn",
    "Mạnh",
    "Mão",
    "Mạo",
    "Mẫn",
    "Mầu",
    "Mậu",
    "Mây",
    "Mịch",
    "Minh",
    "Mít",
    "Mộc",
    "Mưu",
    "Nam",
    "Năm",
    "Năng",
    "Nga",
    "Ngạc",
    "Ngãi",
    "Ngạn",
    "Ngân",
    "Nghê",
    "Nghệ",
    "Nghi",
    "Nghị",
    "Nghĩa",
    "Nghiêm",
    "Nghiên",
    "Nghiệp",
    "Nghinh",
    "Ngọ",
    "Ngoã",
    "Ngoan",
    "Ngoạn",
    "Ngọc",
    "Ngô",
    "Ngộ",
    "Ngôn",
    "Ngũ",
    "Ngụ",
    "Ngung",
    "Nguyên",
    "Nguyện",
    "Nguyệt",
    "Ngữ",
    "Ngự",
    "Nhã",
    "Nhạc",
    "Nham",
    "Nhâm",
    "Nhan",
    "Nhàn",
    "Nhạn",
    "Nhậm",
    "Nhân",
    "Nhẫn",
    "Nhất",
    "Nhật",
    "Nhi",
    "Nhĩ",
    "Nhiệm",
    "Nhiên",
    "Nhiếp",
    "Nhiêu",
    "Nhiễu",
    "Nho",
    "Nhu",
    "Nhuận",
    "Nhuệ",
    "Nhung",
    "Như",
    "Nhự",
    "Nhưỡng",
    "Niêm",
    "Niệm",
    "Niên",
    "Ninh",
    "Nội",
    "Nông",
    "Nữ",
    "Nương",
    "Oai",
    "Oanh",
    "Oánh",
    "Ơn",
    "Phả",
    "Phách",
    "Phái",
    "Phàm",
    "Phạm",
    "Phan",
    "Phán",
    "Phát",
    "Phấn",
    "Phê",
    "Phi",
    "Phiên",
    "Phiến",
    "Phiệt",
    "Phiêu",
    "Phó",
    "Phong",
    "Phóng",
    "Phòng",
    "Phô",
    "Phổ",
    "Phồn",
    "Phu",
    "Phú",
    "Phủ",
    "Phụ",
    "Phúc",
    "Phục",
    "Phùng",
    "Phụng",
    "Phức",
    "Phước",
    "Phương",
    "Phượng",
    "Qua",
    "Quá",
    "Quả",
    "Quan",
    "Quán",
    "Quản",
    "Quang",
    "Quảng",
    "Quân",
    "Quận",
    "Quế",
    "Quốc",
    "Quít",
    "Quy",
    "Quý",
    "Quỳ",
    "Quyên",
    "Quyến",
    "Quyền",
    "Quyết",
    "Quýnh",
    "Quỳnh",
    "Sách",
    "Sám",
    "San",
    "Sang",
    "Sáng",
    "Sanh",
    "Sảnh",
    "Sao",
    "Sát",
    "Sắc",
    "Sâm",
    "Sinh",
    "Sĩ",
    "Siêu",
    "Sinh",
    "Sính",
    "Soạn",
    "Song",
    "Sở",
    "Sơn",
    "Sung",
    "Sử",
    "Sứ",
    "Sự",
    "Sương",
    "Sửu",
    "Tá",
    "Tạ",
    "Tác",
    "Tài",
    "Tác",
    "Tam",
    "Tám",
    "Tạo",
    "Tăng",
    "Tâm",
    "Tầm",
    "Tân",
    "Tấn",
    "Tần",
    "Tập",
    "Tất",
    "Tây",
    "Tế",
    "Thạch",
    "Thaí",
    "Thảng",
    "Thanh",
    "Thành",
    "Thạnh",
    "Thao",
    "Thảo",
    "Thăng",
    "Thắng",
    "Thân",
    "Thận",
    "Thập",
    "Thâu",
    "Thế",
    "Thể",
    "Thi",
    "Thí",
    "Thì",
    "Thị",
    "Thích",
    "Thiên",
    "Thiện",
    "Thiệp",
    "Thiết",
    "Thinh",
    "Thịnh",
    "Thọ",
    "Thoa",
    "Thoả",
    "Thoại",
    "Thoàn",
    "Thôi",
    "Thông",
    "Thống",
    "Thời",
    "Thu",
    "Thủ",
    "Thụ",
    "Thuấn",
    "Thuần",
    "Thuận",
    "Thuật",
    "Thúc",
    "Thục",
    "Thuý",
    "Thuỳ",
    "Thuỷ",
    "Thuỵ",
    "Thuyên",
    "Thuyết",
    "Thư",
    "Thứ",
    "Thừa",
    "Thức",
    "Thực",
    "Thước",
    "Thược",
    "Thương",
    "Thường",
    "Thưởng",
    "Thượng",
    "Thy",
    "Tích",
    "Tiêm",
    "Tiềm",
    "Tiên",
    "Tiến",
    "Tiển",
    "Tiễn",
    "Tiếp",
    "Tiết",
    "Tiêu",
    "Tiếu",
    "Tín",
    "Tinh",
    "Tính",
    "Tình",
    "Tỉnh",
    "Tĩnh",
    "Toa",
    "Toả",
    "Toại",
    "Toan",
    "Toán",
    "Toàn",
    "Toản",
    "Toát",
    "Tòng",
    "Tô",
    "Tố",
    "Tộ",
    "Tổ",
    "Tôn",
    "Tồn",
    "Tống",
    "Tốt",
    "Trà",
    "Trác",
    "Trạc",
    "Trạch",
    "Trai",
    "Trang",
    "Tráng",
    "Tràng",
    "Trạng",
    "Trát",
    "Trắc",
    "Trâm",
    "Trầm",
    "Trân",
    "Trấn",
    "Trần",
    "Tri",
    "Trí",
    "Trì",
    "Trị",
    "Trích",
    "Triêm",
    "Triển",
    "Triết",
    "Triều",
    "Triệu",
    "Trinh",
    "Trình",
    "Trịnh",
    "Trọng",
    "Trợ",
    "Trụ",
    "Truật",
    "Trúc",
    "Trung",
    "Truyền",
    "Trữ",
    "Trứ",
    "Trực",
    "Trưng",
    "Trừng",
    "Trước",
    "Trương",
    "Trường",
    "Trưởng",
    "Tú",
    "Tuân",
    "Tuấn",
    "Tuần",
    "Túc",
    "Tuế",
    "Tuệ",
    "Tung",
    "Tùng",
    "Tụng",
    "Tuy",
    "Tuý",
    "Tuỵ",
    "Tuyên",
    "Tuyến",
    "Tuyền",
    "Tuyển",
    "Tuyết",
    "Tư",
    "Tứ",
    "Từ",
    "Tự",
    "Tước",
    "Tương",
    "Tường",
    "Tưởng",
    "Tửu",
    "Tựu",
    "Ty",
    "Tý",
    "Tỵ",
    "Uẩn",
    "Uy",
    "Uỷ",
    "Uyên",
    "Uyển",
    "ƯÔng",
    "Ưu",
    "Vang",
    "Văn",
    "Vân",
    "Vệ",
    "Vị",
    "Viên",
    "Viễn",
    "Viện",
    "Việt",
    "Vinh",
    "Vĩnh",
    "Vịnh",
    "Võ",
    "Vọng",
    "Vũ",
    "Vui",
    "Vỹ",
    "Vương",
    "Vượng",
    "Xa",
    "Xá",
    "Xoài",
    "Xuân",
    "Xuyên",
    "Xuyến",
    "Xương",
    "Xướng",
    "Yêm",
    "Yểm",
    "Yên",
    "Yến",
]




ADDRESS = [
    "Hoàng Hữu Nam, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "262 Hoàng Hữu Nam, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh 700000, Vietnam",
    "43 Đường Số 245, khu phố 5, Quận 9, Thành phố Hồ Chí Minh 700000, Vietnam",
    "Đường Số 2, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "20/1/3 Đường Số 295, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh 700000, Vietnam",
    "1 Đường Số 2, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "Đường Số 2, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "VR79+87H, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "VR79+87H, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "12/86C Đ. Lê Văn Việt, Phường Tân Phú, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "179 Đ. Lê Văn Việt, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "72 Đ. Lê Văn Việt, Phường Tân Phú, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "Lô I5-3a, 3b, Khu Công Nghệ Cao, Tăng Nhơn Phú A, Thành Phố Thủ Đức, Thành phố Hồ Chí Minh, Vietnam",
    "Lot I-5C Saigon Hi-Tech Park, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "Lô I5-1, đường N7, Khu Công Nghệ Cao, Phường Tăng Nhơn Phú A, Hồ Chí Minh, Vietnam",
    "Khu Công Nghệ Cao, Long Thạnh Mỹ, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "7/11A,Đường 182,Phường Tăng Nhơn Phú A,Quận 9,Tp, Thành phố Hồ Chí Minh 70000, Vietnam",
    "4 Số 12, Tăng Nhơn Phú A, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "15D Số 12, Tăng Nhơn Phú A, Quận 9, Thành phố Hồ Chí Minh, Vietnam",
    "14A Số 12, Khu Phố 4, Quận 9, Thành phố Hồ Chí Minh 700000, Vietnam",
    "RQQW+HJX, Tăng Nhơn Phú A, Quận 9, Quận 9 Hồ Chí Minh, Vietnam",
]


PUBLISHERS = [
    {"name": "Hồng Đức", "address": "65 Tràng Thi, Hà Nội"},
    {"name": "Kim đồng", "address": "55 Quang Trung, Hà Nội, Việt Nam"},
    {"name": "Trẻ", "address": "161B Lý Chính Thắng - P.3 - Q.7 - TP. HCM"},
    {"name": "Đà Nẵng", "address": "Lô 103 Đường 30/4, phường Hòa Cường Bắc, Quận Hải Châu, TP. Đà Nẵng"},
    {"name": "Thuận Hóa Huế", "address": "33 Chu Văn An, Phường Phú Hội, Thừa Thiên Huế"},
    {"name": "Tuệ Lâm Linh", "address": "Số 15 , Ngõ 2 Thọ Tháp , Cầu Giấy , Hà Nội"},
]


BRANCHES = [
    "Đà Nẵng",
    "Hồ Chí Minh",
    "Nha Trang",
    "Hà Nội",
    "Huế",
]
